- id: '1672512021653'
  alias: Kid Room - Auto Dehumidify On
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kid_room_sensor
    above: '60'
    attribute: humidity
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.kid_room_dehumidify
  mode: single
- id: '1672512548497'
  alias: Kid Room - Auto Dehumidify Off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kid_room_sensor
    below: '50'
    attribute: humidity
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.kid_room_dehumidify
  mode: single
- id: '1672512996986'
  alias: Kid Room - Auto Heater On
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kid_room_sensor
    below: '15'
    attribute: temperature
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.kid_room_heater
  mode: single
- id: '1672876799845'
  alias: Kid Room - Auto Heater Off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kid_room_sensor
    above: '17'
    attribute: temperature
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.kid_room_heater
  mode: single
- id: '1674866322296'
  alias: Alex Phone - Battery Low Notification
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.alex_phone_battery_level
    below: '25'
  condition:
  - condition: state
    entity_id: binary_sensor.alex_phone_is_charging
    state: '''Off'''
  action:
  - service: notify.mobile_app_alex_phone
    data:
      message: Phone battery is at 25%. Get to a charger ready.
      title: Phone Battery Low
  mode: single
