# Switchbot Motion Get JSON
command_line: 
  - sensor:
      name: 'Dining Motion'
      scan_interval: 60
      command_timeout: 30
      command: !secret SwitchbotMotionCmd
      value_template: '{{ value_json }}'
      json_attributes:
        - moveDetected
        - brightness

# Switchbot Motion Template
Template:
  - sensor:
      - name: 'Dining Motion Dectected'
        icon: mdi:motion-sensor
        state: "{{ state_attr('sensor.dining_motion', 'moveDetected') }}"
  - sensor:
      - name: 'Dining Motion Brightness'
        icon: mdi:brightness-6
        state: >
          {% set brightness = state_attr('sensor.dining_motion', 'brightness') %}
          {% if brightness == 'bright' %}Bright
          {% elif brightness == 'dim' %}Dim
          {% else %}{{ brightness }}
          {% endif %}
